author:
  avatar:
    url: /images/avatar.jpg
  sns:
    - icon: { name: envelope, options: { type: "fa" } }
      link: mailto:ï¼ƒ
    - icon: { name: fab github, options: { type: "fa" } }
      link: https://github.com/camellusforest

head:
  favicons:
    - rel: icon
      type: image/png
      sizes: 16x16
      href: /images/favicon/favicon-16x16.png
    - rel: icon
      type: image/png
      sizes: 32x32
      href: /images/favicon/favicon-32x32.png
    - rel: apple-touch-icon
      sizes: 180x180
      href: /images/favicon/apple-touch-icon.png
  #   - rel: mask-icon
  #     color: white
  #     href: /images/favicon/xin.svg
  theme_color: "#414852"

post:
  cc: by-nc-sa

google_analytics:
  tracking_id: UA-132230328-1

menu:
  home: { enable: true }
  tags: { enable: true }
  categories: { enable: true }
  archives: { enable: true }
  about:
    #     path: /more/
    path: https://camellusforest.netlify.app/2099/01/01/about-this-example/
    icon: { name: info-circle, options: { type: "fa" } }
# comment:
#   - name: disqus
#     options:
#       shortname: jiangtj
# - name: utteranc
#   options:
#     repo: jiangtj-lab/comments-test
# - name: livere
#   options:
#     uid: MTAyMC80MzMyNi8xOTg2Nw==

#chatra:
#  enable: true
#  async: true
#  id: BBphpQAouKacekeKq
